[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain>=1.4.0",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.11",
    "ml",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "shared",
    "uvicorn>=0.53.0",
]

[tool.uv.sources]
shared = { path = "../shared", editable = true }
ml = { path = "../ml", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.7",
]
